/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.dao;

import bit.project.server.entity.Customer;
import bit.project.server.entity.Sale;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.time.LocalDate;

@RepositoryRestResource(exported=false)
public interface CustomerDao extends JpaRepository<Customer, Integer>{


    Customer findByNic(String nic);
    Customer findByContact1(String contact1);
    Customer findByName(String name);



    @Query("select count(c) from Customer c where c.regdate>=:startdate and c.regdate<=:enddate")
    Long getCustomerCountByRange(@Param("startdate")LocalDate startdate, @Param("enddate") LocalDate enddate);
}
